<a href="https://colab.research.google.com/github/Khislatz/DS-Unit-2-Linear-Models/blob/master/module3-ridge-regression/Khislat_Zhuraeva_LS_DS_213_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 3*

---

# Ridge Regression

## Assignment

We're going back to our other **New York City** real estate dataset. Instead of predicting apartment rents, you'll predict property sales prices.

But not just for condos in Tribeca...

- [ ] Use a subset of the data where `BUILDING_CLASS_CATEGORY` == `'01 ONE FAMILY DWELLINGS'` and the sale price was more than 100 thousand and less than 2 million.
- [ ] Do train/test split. Use data from January — March 2019 to train. Use data from April 2019 to test.
- [ ] Do one-hot encoding of categorical features.
- [ ] Do feature selection with `SelectKBest`.
- [ ] Fit a ridge regression model with multiple features. Use the `normalize=True` parameter (or do [feature scaling](https://scikit-learn.org/stable/modules/preprocessing.html) beforehand — use the scaler's `fit_transform` method with the train set, and the scaler's `transform` method with the test set)
- [ ] Get mean absolute error for the test set.
- [ ] As always, commit your notebook to your fork of the GitHub repo.

The [NYC Department of Finance](https://www1.nyc.gov/site/finance/taxes/property-rolling-sales-data.page) has a glossary of property sales terms and NYC Building Class Code Descriptions. The data comes from the [NYC OpenData](https://data.cityofnewyork.us/browse?q=NYC%20calendar%20sales) portal.


## Stretch Goals

Don't worry, you aren't expected to do all these stretch goals! These are just ideas to consider and choose from.

- [ ] Add your own stretch goal(s) !
- [ ] Instead of `Ridge`, try `LinearRegression`. Depending on how many features you select, your errors will probably blow up! 💥
- [ ] Instead of `Ridge`, try [`RidgeCV`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeCV.html).
- [ ] Learn more about feature selection:
    - ["Permutation importance"](https://www.kaggle.com/dansbecker/permutation-importance)
    - [scikit-learn's User Guide for Feature Selection](https://scikit-learn.org/stable/modules/feature_selection.html)
    - [mlxtend](http://rasbt.github.io/mlxtend/) library
    - scikit-learn-contrib libraries: [boruta_py](https://github.com/scikit-learn-contrib/boruta_py) & [stability-selection](https://github.com/scikit-learn-contrib/stability-selection)
    - [_Feature Engineering and Selection_](http://www.feat.engineering/) by Kuhn & Johnson.
- [ ] Try [statsmodels](https://www.statsmodels.org/stable/index.html) if you’re interested in more inferential statistical approach to linear regression and feature selection, looking at p values and 95% confidence intervals for the coefficients.
- [ ] Read [_An Introduction to Statistical Learning_](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf), Chapters 1-3, for more math & theory, but in an accessible, readable way.
- [ ] Try [scikit-learn pipelines](https://scikit-learn.org/stable/modules/compose.html).

In [0]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Applied-Modeling/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'
    
# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [0]:
import pandas as pd
import pandas_profiling

# Read New York City property sales data
df = pd.read_csv(DATA_PATH+'condos/NYC_Citywide_Rolling_Calendar_Sales.csv')

# Change column names: replace spaces with underscores
df.columns = [col.replace(' ', '_') for col in df]

# SALE_PRICE was read as strings.
# Remove symbols, convert to integer
df['SALE_PRICE'] = (
    df['SALE_PRICE']
    .str.replace('$','')
    .str.replace('-','')
    .str.replace(',','')
    .astype(int)
)

In [0]:
# BOROUGH is a numeric column, but arguably should be a categorical feature,
# so convert it from a number to a string
df['BOROUGH'] = df['BOROUGH'].astype(str)

In [0]:
# Reduce cardinality for NEIGHBORHOOD feature

# Get a list of the top 10 neighborhoods
top10 = df['NEIGHBORHOOD'].value_counts()[:10].index

# At locations where the neighborhood is NOT in the top 10, 
# replace the neighborhood with 'OTHER'
df.loc[~df['NEIGHBORHOOD'].isin(top10), 'NEIGHBORHOOD'] = 'OTHER'

In [6]:
df.head(2)

BOROUGH NEIGHBORHOOD  ... SALE_PRICE   SALE_DATE
0       1        OTHER  ...          0  01/01/2019
1       1        OTHER  ...          0  01/01/2019

[2 rows x 21 columns]

In [7]:
df['SALE_PRICE'].unique() 

array([     0, 550000, 200000, ..., 689419, 574850, 892500])

# Use a subset of the data where BUILDING_CLASS_CATEGORY == '01 ONE FAMILY DWELLINGS' and the sale price was more than 100 thousand and less than 2 million.

In [8]:
#creating a subset 
df_sub = df.loc[(df['BUILDING_CLASS_CATEGORY'] == '01 ONE FAMILY DWELLINGS') & ((df['SALE_PRICE']>100000) & (df['SALE_PRICE']<2000000))]
df_sub['SALE_PRICE']

44       550000
61       200000
78       810000
108      125000
111      620000
          ...  
23029    635000
23031    514000
23032    635000
23033    545000
23035    510000
Name: SALE_PRICE, Length: 3151, dtype: int64

In [93]:
df_sub.dropna(axis=1, how = 'any', inplace=True)
df_sub.head(3)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


BOROUGH NEIGHBORHOOD  ... SALE_PRICE   SALE_DATE
44       3        OTHER  ...     550000  01/01/2019
61       4        OTHER  ...     200000  01/01/2019
78       2        OTHER  ...     810000  01/02/2019

[3 rows x 19 columns]

In [0]:
train = df_sub[(df_sub['SALE_DATE'] >= '01/01/2019') & (df_sub['SALE_DATE'] < '04/01/2019')] # train data from January through March 2019
test = df_sub[(df_sub['SALE_DATE'] >= '04/01/2019') & (df_sub['SALE_DATE'] <= '04/30/2019')] #test data from April 2019

In [95]:
train.shape, test.shape

((2507, 19), (644, 19))

In [96]:
train.describe(exclude='number')

BOROUGH NEIGHBORHOOD  ... BUILDING_CLASS_AT_TIME_OF_SALE   SALE_DATE
count     2507         2507  ...                           2507        2507
unique       5            7  ...                             11          68
top          4        OTHER  ...                             A1  01/31/2019
freq      1204         2360  ...                            919          78

[4 rows x 9 columns]

In [97]:
train.dtypes.head()
# train.select_dtypes(include='number').describe()

BOROUGH                    object
NEIGHBORHOOD               object
BUILDING_CLASS_CATEGORY    object
TAX_CLASS_AT_PRESENT       object
BLOCK                       int64
dtype: object

In [98]:
target = 'SALE_PRICE'
high_cardinality = ['ADDRESS', 'LAND_SQUARE_FEET', 'SALE_DATE']
features = train.columns.drop([target] + high_cardinality)
features

Index(['BOROUGH', 'NEIGHBORHOOD', 'BUILDING_CLASS_CATEGORY',
       'TAX_CLASS_AT_PRESENT', 'BLOCK', 'LOT', 'BUILDING_CLASS_AT_PRESENT',
       'ZIP_CODE', 'RESIDENTIAL_UNITS', 'COMMERCIAL_UNITS', 'TOTAL_UNITS',
       'GROSS_SQUARE_FEET', 'YEAR_BUILT', 'TAX_CLASS_AT_TIME_OF_SALE',
       'BUILDING_CLASS_AT_TIME_OF_SALE'],
      dtype='object')

In [99]:
[target] + high_cardinality

['SALE_PRICE', 'ADDRESS', 'LAND_SQUARE_FEET', 'SALE_DATE']

In [0]:
X_train = train[features]
y_train = train[target]
X_test = test[features]
y_test = test[target]

In [101]:
X_train.head()

BOROUGH  ... BUILDING_CLASS_AT_TIME_OF_SALE
44        3  ...                             A9
61        4  ...                             A1
78        2  ...                             A1
108       3  ...                             A1
111       3  ...                             A5

[5 rows x 15 columns]

# Do one-hot encoding of categorical features.

In [0]:
import category_encoders as ce

encoder = ce.one_hot.OneHotEncoder(use_cat_names=True)
X_train_enc = encoder.fit_transform(X_train)
#or we can write
#encoder.fit(X_train)
#X_train_enc = encoder.transform(X_train)
X_test_enc  = encoder.transform(X_test) #We only use encoder.transform on test data (no fit)

In [103]:
X_test_enc.head()

BOROUGH_3  ...  BUILDING_CLASS_AT_TIME_OF_SALE_S0
18235          0  ...                                  0
18239          0  ...                                  0
18244          1  ...                                  0
18280          1  ...                                  0
18285          1  ...                                  0

[5 rows x 48 columns]

In [0]:
def engineer_features(X):
  X = X.copy()
  return X

X_train_eng = engineer_features(X_train_enc)
X_test_eng = engineer_features(X_test_enc)

 # Do feature selection with SelectKBest.

In [105]:
# How many features do we have currently?
features = X_train_eng.columns
n = len(features)
n

48

In [106]:
# How many ways to choose 1 to n features?
from math import factorial

def n_choose_k(n, k):
    return factorial(n)/(factorial(k)*factorial(n-k))

combinations = sum(n_choose_k(n,k) for k in range(1,n+1))
print(f'{combinations:,.0f}')

281,474,976,710,655


In [107]:
X_train.shape, X_train_enc.shape, X_test.shape, X_test_enc.shape

((2507, 15), (2507, 48), (644, 15), (644, 48))

In [108]:
X_train_eng.isnull().sum().head(3)

BOROUGH_3    0
BOROUGH_4    0
BOROUGH_2    0
dtype: int64

In [0]:
import numpy as np
np.seterr(divide='ignore', invalid='ignore')
from sklearn.feature_selection import SelectKBest, f_regression
selector = SelectKBest(score_func=f_regression, k=20)
X_train_kbest = selector.fit_transform(X_train_eng, y_train)
X_test_kbest = selector.transform(X_test_eng)



In [119]:
X_train_kbest.shape, X_test_kbest.shape

((2507, 20), (644, 20))

In [120]:
X_train_kbest

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [121]:
# TODO: Which features were selected?
mask = selector.get_support()
mask

array([ True, False,  True,  True, False,  True,  True, False, False,
        True,  True, False, False, False, False,  True, False, False,
       False,  True, False, False,  True,  True, False,  True, False,
       False, False, False,  True, False,  True,  True,  True, False,
       False, False, False,  True, False, False,  True,  True, False,
        True, False, False])

In [122]:
X_train_eng.columns[mask]

Index(['BOROUGH_3', 'BOROUGH_2', 'BOROUGH_5', 'NEIGHBORHOOD_OTHER',
       'NEIGHBORHOOD_FLUSHING-NORTH', 'NEIGHBORHOOD_FOREST HILLS',
       'NEIGHBORHOOD_BOROUGH PARK', 'BLOCK', 'BUILDING_CLASS_AT_PRESENT_A5',
       'BUILDING_CLASS_AT_PRESENT_A3', 'BUILDING_CLASS_AT_PRESENT_S1',
       'BUILDING_CLASS_AT_PRESENT_A6', 'ZIP_CODE', 'COMMERCIAL_UNITS',
       'TOTAL_UNITS', 'GROSS_SQUARE_FEET', 'BUILDING_CLASS_AT_TIME_OF_SALE_A5',
       'BUILDING_CLASS_AT_TIME_OF_SALE_A3',
       'BUILDING_CLASS_AT_TIME_OF_SALE_S1',
       'BUILDING_CLASS_AT_TIME_OF_SALE_A6'],
      dtype='object')

In [123]:
X_train_eng.columns[~mask]

Index(['BOROUGH_4', 'BOROUGH_1', 'NEIGHBORHOOD_EAST NEW YORK',
       'NEIGHBORHOOD_BEDFORD STUYVESANT', 'NEIGHBORHOOD_ASTORIA',
       'BUILDING_CLASS_CATEGORY_01 ONE FAMILY DWELLINGS',
       'TAX_CLASS_AT_PRESENT_1', 'TAX_CLASS_AT_PRESENT_1D', 'LOT',
       'BUILDING_CLASS_AT_PRESENT_A9', 'BUILDING_CLASS_AT_PRESENT_A1',
       'BUILDING_CLASS_AT_PRESENT_A0', 'BUILDING_CLASS_AT_PRESENT_A2',
       'BUILDING_CLASS_AT_PRESENT_A4', 'BUILDING_CLASS_AT_PRESENT_A8',
       'BUILDING_CLASS_AT_PRESENT_B2', 'BUILDING_CLASS_AT_PRESENT_S0',
       'BUILDING_CLASS_AT_PRESENT_B3', 'RESIDENTIAL_UNITS', 'YEAR_BUILT',
       'TAX_CLASS_AT_TIME_OF_SALE', 'BUILDING_CLASS_AT_TIME_OF_SALE_A9',
       'BUILDING_CLASS_AT_TIME_OF_SALE_A1',
       'BUILDING_CLASS_AT_TIME_OF_SALE_A0',
       'BUILDING_CLASS_AT_TIME_OF_SALE_A2',
       'BUILDING_CLASS_AT_TIME_OF_SALE_A4',
       'BUILDING_CLASS_AT_TIME_OF_SALE_A8',
       'BUILDING_CLASS_AT_TIME_OF_SALE_S0'],
      dtype='object')

In [124]:
# TODO: How many features should be selected?

# You can try a range of values for k,
# then choose the model with the best score.
# If multiple models "tie" for the best score,
# choose the simplest model.
# You decide what counts as a tie!
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

mae_list = []
for k in range(1, X_train_eng.shape[1]+1):
  print(f'{k} features')
  selector = SelectKBest(score_func=f_regression, k=k)
  X_train_kbest = selector.fit_transform(X_train_eng, y_train)
  X_test_kbest = selector.transform(X_test_eng)
  model = LinearRegression()
  model.fit(X_train_kbest, y_train)
  y_pred = model.predict(X_test_kbest)
  mae = mean_absolute_error(y_pred, y_test)
  print(f'MAE on test set: ${mae:.2f}')
  mae_list.append(mae)

1 features
MAE on test set: $183640.59
2 features
MAE on test set: $182569.26
3 features
MAE on test set: $182569.26
4 features
MAE on test set: $183440.75
5 features
MAE on test set: $181935.13
6 features
MAE on test set: $176456.32
7 features
MAE on test set: $177001.36
8 features
MAE on test set: $176707.36
9 features
MAE on test set: $171663.46
10 features
MAE on test set: $170976.54
11 features
MAE on test set: $170506.83
12 features
MAE on test set: $162300.68
13 features
MAE on test set: $163558.86
14 features
MAE on test set: $162562.33
15 features
MAE on test set: $162563.55
16 features
MAE on test set: $162419.48
17 features
MAE on test set: $162419.48
18 features
MAE on test set: $162177.33
19 features
MAE on test set: $162177.33
20 features
MAE on test set: $157892.53
21 features
MAE on test set: $157965.58
22 features
MAE on test set: $157965.58
23 features
MAE on test set: $157965.58
24 features
MAE on test set: $157965.58
25 features
MAE on test set: $157696.75
26 featur